// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/garcia-paulo/go-gin/application/middlewares/auth"
	"github.com/garcia-paulo/go-gin/application/servicers"
	"github.com/garcia-paulo/go-gin/application/token"
	"github.com/garcia-paulo/go-gin/infra/config"
	"github.com/garcia-paulo/go-gin/infra/database"
	"github.com/garcia-paulo/go-gin/infra/repositories"
	"github.com/garcia-paulo/go-gin/presentation/controllers"
	"github.com/garcia-paulo/go-gin/presentation/routes"
)

// Injectors from wire.go:

func InitializeRoutes() *routes.Server {
	configConfig := config.NewConfig()
	db := database.NewDatabase(configConfig)
	studentRepository := repositories.NewStudentRepository(db)
	studentServicer := servicers.NewStudentServicer(studentRepository)
	studentController := controllers.NewStudentController(studentServicer)
	tokenMaker := token.NewTokenMaker(configConfig)
	authMiddleware := middlewares_auth.NewAuthMiddleware(tokenMaker)
	studentRoutes := routes.NewStudentRoutes(studentController, authMiddleware)
	userRepository := repositories.NewUserRepository(db)
	userServicer := servicers.NewUserServicer(userRepository, tokenMaker, configConfig)
	userController := controllers.NewUserController(userServicer)
	userRoutes := routes.NewUserRoutes(userController)
	server := routes.NewServer(studentRoutes, userRoutes, configConfig)
	return server
}
