// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/garcia-paulo/go-gin/Application/servicers"
	"github.com/garcia-paulo/go-gin/Infra/database"
	"github.com/garcia-paulo/go-gin/Infra/repositories"
	"github.com/garcia-paulo/go-gin/Presentation/controllers"
	"github.com/garcia-paulo/go-gin/Presentation/routes"
)

// Injectors from wire.go:

func InitializeRoutes() *routes.Routes {
	db := database.NewDatabase()
	studentRepository := repositories.NewStudentRepository(db)
	studentServicer := servicers.NewStudentServicer(studentRepository)
	studentController := controllers.NewStudentController(studentServicer)
	routesRoutes := routes.NewRoutes(studentController)
	return routesRoutes
}
