// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/garcia-paulo/go-gin/application/servicers"
	"github.com/garcia-paulo/go-gin/infra/database"
	"github.com/garcia-paulo/go-gin/infra/repositories"
	"github.com/garcia-paulo/go-gin/presentation/controllers"
	"github.com/garcia-paulo/go-gin/presentation/routes"
)

// Injectors from wire.go:

func InitializeRoutes() *routes.Server {
	db := database.NewDatabase()
	studentRepository := repositories.NewStudentRepository(db)
	studentServicer := servicers.NewStudentServicer(studentRepository)
	studentController := controllers.NewStudentController(studentServicer)
	studentRoutes := routes.NewRoutes(studentController)
	server := routes.NewServer(studentRoutes)
	return server
}
